// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqp1HovxObnTNu3DhEhR-s3TYCChT3Cs',
    appId: '1:1097189903082:web:ef3c0e7dc4cfd1cbb0e593',
    messagingSenderId: '1097189903082',
    projectId: 'analytic-s',
    authDomain: 'analytic-s.firebaseapp.com',
    storageBucket: 'analytic-s.appspot.com',
    measurementId: 'G-1VF8SMKH07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60v36t7il1xN6wqN0ze2f11k5vUcw7GY',
    appId: '1:1097189903082:android:f60b531207d8888cb0e593',
    messagingSenderId: '1097189903082',
    projectId: 'analytic-s',
    storageBucket: 'analytic-s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqdj0PEEOtI5sWjm65i9K3BfBI1G-svcI',
    appId: '1:1097189903082:ios:f4a033ffe0ae5e3fb0e593',
    messagingSenderId: '1097189903082',
    projectId: 'analytic-s',
    storageBucket: 'analytic-s.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqdj0PEEOtI5sWjm65i9K3BfBI1G-svcI',
    appId: '1:1097189903082:ios:f4a033ffe0ae5e3fb0e593',
    messagingSenderId: '1097189903082',
    projectId: 'analytic-s',
    storageBucket: 'analytic-s.appspot.com',
    iosBundleId: 'com.example.frontend',
  );
}
